version: '2'
services:
    backendapi-app:
        image: backendapi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@192.168.25.128:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://backendapi-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=backendapi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    backendapi-mongodb:
        extends:
            file: mongodb.yml
            service: backendapi-mongodb
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
